### PR TITLE
feat: add internal barrel exports and fix eslint prettier

### PR DESCRIPTION
**Pull request by macseem**

### CODE REVIEW

**Review by vitalyiegorov — DISMISSED** [review]

**Comment by vitalyiegorov** [comment]
@macseem You need to commit `yarn.lock` changes https://app.travis-ci.com https://app.travis-ci.com/github/rnw-community/rnw-community

**Comment by macseem** [comment]
when I do yarn install - I have no changes.
i bet it's the yarn version in travis, can you set it to 3.4.1?

**Comment by macseem** [comment]
this might be the case, but I'm not sure
Screenshot 2023-03-20 at 23 30 25

**Comment by macseem** [comment]
for ref - different architectures, added all possible so far to bypass it into dev deps in here #134

**Review by vitalyiegorov — APPROVED** [review]

**Pull request merged**
