### PR TITLE
feat: updated react-native-payments-example to the latest RN 0.74

### LINKED ISSUE #185: react-native-payments does not work with react-native >= 0.72.13
First of all thank you very much for rewriting and maintaining this library. We are using it for a while now and it worked like a charm.

Recently we were upgrade our react-native version from 0.72.12 to 0.72.13 and unfortunately the lib stopped working on both iOS & Android. All we see now is a white screen without any errors. After debugging we found out that removing the library is the only way for our app to work again.

I cannot seem to find the issue since the react-native upgrade was only a patch version.
https://github.com/facebook/react-native/blob/main/CHANGELOG.md#v07213

We'd really appreciate your help :)

### PR DESCRIPTION
**Pull request by vitalyiegorov**
closes #185 

- Updated `react-native-payments-example` package to the latest RN 0.74
- Fixed IOS PK* supported networks mapping
- Upgraded turbo to v2

### CODE REVIEW

**Review by AhmedHashem2105 — COMMENTED** [review]
mada support completed

**Review by AhmedHashem2105 — APPROVED** [review]
mada support completed

**Comment by AhmedHashem2105** [comment]
it needs to be approved but i can't approve merge request

**Comment by vitalyiegorov** [comment]
@AhmedHashem2105 in 15 minutes new version will be published to npm

**Comment by AhmedHashem2105** [comment]
Thanks for u, I wait the update on @rnw-community/react-native-payments

**Comment by AhmedHashem2105** [comment]
when i console.log(err) in NativePayments, i gives the screenshot in
console in this function in node_modules

show(): Promise<AndroidPaymentResponse | IosPaymentResponse> {
return new Promise<AndroidPaymentResponse | IosPaymentResponse>((resolve,
reject) => {
this.acceptPromiseRejecter = reject;

if (this.state === 'created') {
this.state = 'interactive';

// HINT: We need to pass Android environment configuration to native module
via details
const details = isAndroid
? {
...this.details,
environment: (this.platformMethodData as
AndroidPaymentMethodDataDataInterface).environment,
}
: this.details;

NativePayments.show(this.serializedMethodData, details)
.then(jsonDetails => {
resolve(this.handleAccept(jsonDetails));

return void 0;
})
.catch(reject);
} else {
reject(new DOMException(PaymentsErrorEnum.InvalidStateError));
}
});
}

**Pull request merged**
